- yarn.lock
Updates `yarn.lock` and pins `@0x/quote-server` to the latest version
> updated lockfile

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
Makes the default gas schedule Required so it breaks when a source is missing.
> fix: asset-swapper Set the FeeSchedule to Required

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
- updating Kovan's erc20BridgeSampler to `0x298a99d3a2b891df04019425542897ac1a867d9d`
- 0x-API PR: https://github.com/0xProject/0x-api/pull/396
> fix: update kovan erc20BridgeSampler

- contracts/asset-proxy/contracts/src/bridges/ShellBridge.sol
- contracts/utils/contracts/src/DeploymentConstants.sol
- contracts/zero-ex/contracts/src/transformers/bridges/BridgeAdapter.sol
- contracts/zero-ex/contracts/src/transformers/bridges/mixins/MixinAdapterAddresses.sol
- contracts/zero-ex/contracts/src/transformers/bridges/mixins/MixinShell.sol
- contracts/zero-ex/test/transformers/fill_quote_transformer_test.ts
- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/contracts/src/ShellSampler.sol
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/multibridge_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/orders.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/shell_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
- packages/asset-swapper/test/market_operation_utils_test.ts
- packages/migrations/src/migration.ts
Support Multiple shells.
[Sims with overwritten FQT + BridgeAdapter](https://metabase.spaceship.0x.org/dashboard/139?run_id=exceed-whimsical-business&adjusted_amount_bought_win_tolerance__bps_=0.5)
```json
{
"erc20Proxy": "0x95e6f48254609a6ee006f7d493c8e5fb97094cef",
"exchangeProxy": "0xdef1c0ded9bec7f1a1670819833240f027b25eff",
"exchangeProxyOwnerStorageSlot": "0x0000000000000000000000000000000300000000000000000000000000000000",
"taker": "0xd00d00caca000000000000000000000000001337",
"gst": "0x0000000000b3F879cb30FE243b4Dfee438691c04",
"transformers": {
"deployer": "0x39dce47a67ad34344eab877eae3ef1fa2a1d50bb",
"overridesByNonce": {
"4": {
"artifactPath": "../0x-monorepo/contracts/zero-ex/test/generated-artifacts/FillQuoteTransformer.json",
"constructorArgs": [ …
```
> fix: Support Multiple Shells

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/constants.ts
- packages/asset-swapper/src/swap_quoter.ts
- packages/asset-swapper/src/types.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/index.ts
- packages/asset-swapper/src/utils/market_operation_utils/multihop_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
- packages/asset-swapper/test/dex_sampler_test.ts
- packages/asset-swapper/test/market_operation_utils_test.ts
Uses the `TokenAdjacencyGraph` for Uniswap/Sushi sells in both normal splitting and MultiHop Splitting.
[Sims](https://metabase.spaceship.0x.org/dashboard/139?run_id=practice-straight-reaction&adjusted_amount_bought_win_tolerance__bps_=0.5)
> feat: [asset-swapper] more hops via token adjacency

- contracts/zero-ex/CHANGELOG.json
- contracts/zero-ex/contracts/src/transformers/bridges/mixins/MixinZeroExBridge.sol
- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
Like #28 but through the right transformer deployer. :sweat: 
Also trust the `boughtAmount` returned by LPs.
TODO: Deploy on mainnet.
> Deploy FQT with correct deployer

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/curve_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
- Curve Pools: PAX, hBTC
- Curve Metapools: USD, hUSD, USDn, mUSD, tBTC
- Simbot: https://metabase.spaceship.0x.org/dashboard/139?run_id=new-curve-pools-01
> feat: adding Curve pools: PAX, hBTC, metapools: gUSD, hUSD, USDn, mUSD, tBTC

- contracts/zero-ex/test/protocol_fees_test.ts
These tests cover more of protocol fees. In particular, they add negative test cases around authorization and errors in fee collection. They also test more scenarios around initialized and uninitialized fee collectors.
`yarn build && yarn test` from `contracts/zero-ex`
* more tests
-   [X] Prefix PR title with `[WIP]` if necessary.
-   [X] Add tests to cover changes as needed.
-   [X] Update documentation as needed.
-   [X] Add new entries to the relevant CHANGELOG.jsons.
> better protocol fee tests

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts
- packages/asset-swapper/test/exchange_proxy_swap_quote_consumer_test.ts
> Remove PLP VIP path from EP swap quote consumer

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/package.json
- packages/asset-swapper/src/swap_quoter.ts
- packages/asset-swapper/src/types.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/index.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
- packages/asset-swapper/src/utils/swap_quote_calculator.ts
- packages/asset-swapper/src/utils/utils.ts
- packages/asset-swapper/test/utils/swap_quote.ts
- yarn.lock
Tweak the gas schedule post FQT rollup
Adjust some curves to be the delta mid-transaction rather then the total gross
[Sims](https://metabase.spaceship.0x.org/dashboard/139?run_id=damage-lazy-business&adjusted_amount_bought_win_tolerance__bps_=0.5)
> feat: asset-swapper tweak the gas schedule + return decimals

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/test/dex_sampler_test.ts
Disables off-chain sampling as CREAM seems to be giving wildly inaccurate data on the first request.
> fix: [asset-swapper] disable off-chain sampling for Balancer and CREAM

- docs/advanced/mtx.rst
- docs/advanced/uniswap.rst
- docs/architecture/features.rst
- docs/architecture/proxy.rst
- Include Best Practices for Feature Development.
- Explicitly point out function selector collision and reentrancy in the Known Risks section.
> minor doc updates

- docs/advanced/erc20_transformations.rst
- docs/architecture/features.rst
> Added link to `Transformer Deployer` section + fixed safety checklist

- packages/asset-swapper/src/types.ts
- packages/asset-swapper/src/utils/market_operation_utils/index.ts
Renames interface for firm quote validator
> fix: rename function to Async

- docs/additional/releases.rst
> updated releases

- contracts/staking/compiler.json
Or else it's stuck using whatever is installed.
> `@0x/contracts-staking`: Set `isOfflineMode: false` in `compiler.json`

- docs/advanced/plp.rst
> Point to ILiquidityProvider interface, not ILiquidityProviderSandbox

- packages/asset-swapper/src/utils/market_operation_utils/index.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
- packages/asset-swapper/src/utils/swap_quote_calculator.ts
> fix: handle potentially undefined path

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/liquidity_provider_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
- packages/asset-swapper/test/dex_sampler_test.ts
- packages/asset-swapper/test/market_operation_utils_test.ts
> Reenable PLP VIP and add gasCost field to LiquidityProviderRegistry

- docs/additional/releases.rst
> Synchronize Release Names

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
For the hot-pants release.
Probably shouldn't merge this until we're ready to update API.
> Update mainnet and ropsten transformer addresses

- contracts/zero-ex/CHANGELOG.json
- contracts/zero-ex/test/features/selector_collision_test.ts
Note that this test can raise false positives, because it tests the selectors of _all_ external/public functions of _all_ non-abstract contracts in the `@0x/contracts-zero-ex` package. 
> ExchangeProxy selector collision test

- docs/additional/releases.rst
- docs/basics/functions.rst
- docs/basics/orders.rst
> Updated Releases + Fix Links

- contracts/zero-ex/.npmignore
- contracts/zero-ex/package.json
- contracts/zero-ex/scripts/rollback.ts
- contracts/zero-ex/src/rollback.ts
- contracts/zero-ex/tsconfig.json
- yarn.lock
Adds a script to view information about functions registered to the EP and generate governor calldata for rollbacks.
> Rollback CLI tools

- docs/basics/orders.rst
Adds SRA schema for RFQ orders
> fix: added SRA schema for V4 orders

- contracts/zero-ex/CHANGELOG.json
- contracts/zero-ex/contracts/src/external/FeeCollector.sol
- contracts/zero-ex/contracts/src/external/LiquidityProviderSandbox.sol
- contracts/zero-ex/contracts/src/features/LiquidityProviderFeature.sol
- contracts/zero-ex/contracts/src/features/UniswapFeature.sol
- contracts/zero-ex/contracts/src/transformers/bridges/mixins/MixinZeroExBridge.sol
- contracts/zero-ex/test/features/liquidity_provider_test.ts
- Use `staticcall()` in `ERC20.allowance()` call.
- Revert if ETH is attached to a non-ETH sell.
- Assert `returndatasize()` for `ERC20.allowance()` and `UniswapV2Pair.getReserves()` call.
- Always transfer `msg.value` to the provider.
Comments cleanup in other contracts.
> EP: Address audit feedback

- packages/asset-swapper/src/swap_quoter.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/test/dex_sampler_test.ts
Disables Bancor for Ganache/testnets as it not support
> Disable Bancor Service for non-mainnet

- contracts/zero-ex/scripts/rollback.ts
> Only use subgraph query result to populate function history

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
> `@0x/contract-addresses`: Redeploy FQT

- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
Updates the Shell pools to the new addresses
> chore: [asset-swapper] Update Shells to new version

- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- adding UST, BBTC, OBTC, aDAI, aUSDC, aUSDT, sEUR, EURS, sETH pools
- simbot: https://metabase.spaceship.0x.org/dashboard/139?run_id=new_curve_pools007&adjusted_amount_bought_win_tolerance__bps_=0.5
> feat: adding UST, BBTC, OBTC, aDAI, aUSDC, aUSDT, sEUR, EURS, sETH pools

- contracts/zero-ex/CHANGELOG.json
- contracts/zero-ex/contracts/src/features/UniswapFeature.sol
Make returndatasize checks consistent with solidity ABI-decoding. As per post-audit feedback.
> UniswapFeature: consistent returndatasize checks

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
> Update PLP sandbox addresses

- packages/migrations/CHANGELOG.json
- packages/migrations/Dockerfile
This fixes the unexpected behavior caused by networkId != chainId in the ganache snapshot.
> Update snapshot dockerfile to override networkId and chainId

- docs/additional/releases.rst
Also moved babooshka to 2/08 since that's probably the earliest we'd execute the tx?
> docs: add `big-pantsuit-energy` release

- packages/asset-swapper/src/utils/quote_simulation.ts
- packages/asset-swapper/test/quote_simulation_test.ts
> feat: Don't charge a protocol fee for RFQ orders WIP

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/index.ts
- packages/asset-swapper/src/utils/quote_report_generator.ts
Filter out any two hops where the data just doesn't exist, i.e a route could not be found. Prevents errors downstream where it is expected to exist (quote report)
> fix: [asset-swapper] prevent error when multihop data is not present

- docs/basics/orders.rst
> `docs`: Fix wrong method name for order signature generation

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
> Deploy V4 FQT

- packages/asset-swapper/src/index.ts
- packages/asset-swapper/src/types.ts
- packages/asset-swapper/src/utils/market_operation_utils/balancer_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/cream_utils.ts
- packages/asset-swapper/test/dex_sampler_test.ts
- packages/asset-swapper/test/utils/mock_balancer_pools_cache.ts
https://github.com/0xProject/0x-api/issues/458
Loads the top 250 Balancer pools on construction. So we lower the chance a new instance is missing Balancer pools
> fix: Balancer load top pools

- packages/asset-swapper/src/utils/market_operation_utils/index.ts
Adds few end-to-end latency checks for RFQ
> E2E latency checks

- docs/additional/releases.rst
> Updated releases page

- packages/asset-swapper/contracts/src/BalanceChecker.sol
- packages/asset-swapper/test/contracts/balance_checker_test.ts
Added a new function to BalancerChecker to return the minimum of balance or allowance to a specified address.
Added contract tests.
> added getMinOfBalancesOrAllowances function to BalanceChecker contract

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/index.ts
> fix: Second hop source is missing

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/constants.ts
- packages/asset-swapper/src/index.ts
- packages/asset-swapper/src/swap_quoter.ts
- packages/asset-swapper/src/types.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/token_adjacency_graph_builder.ts
- packages/asset-swapper/test/market_operation_utils_test.ts
Supports the Mirror protocol m* tokens and adjusts the token adjacency when these tokens are involved
Baseline sims (expected no negative impact): https://metabase.spaceship.0x.org/dashboard/139?run_id=mirror-hops-baseline&adjusted_amount_bought_win_tolerance__bps_=0.5
> feat: Mirror Protocol tokens

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
Fixes the gas schedule override into fee schedule setting all Native to include a protocol fee.
> fix: Protocol fee in fee schedule

- packages/asset-swapper/contracts/test/TestNativeOrderSampler.sol
- packages/asset-swapper/test/contracts/native_order_sampler_test.ts
- packages/asset-swapper/test/dex_sampler_test.ts
Re-enabes Native Order sampler tests
> feat: Validate v4 limit orders

- contracts/zero-ex/CHANGELOG.json
- contracts/zero-ex/contracts/src/transformers/bridges/BridgeAdapter.sol
- contracts/zero-ex/contracts/src/transformers/bridges/BridgeSource.sol
- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/orders.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
- packages/asset-swapper/test/dex_sampler_test.ts
- packages/asset-swapper/test/market_operation_utils_test.ts
- packages/protocol-utils/src/transformer_utils.ts
Adds Linkswap with a hop to LINK, ETH
```
SELL YFL->ETH 2.16 -> 0.33 ($649.96) after 0.1s @ dev
✔ PASS 2.16 -> 0.33 ($543.77) ($86.20)
Linkswap: 100%
gas: 276416
SELL ETH->YFL 3.28 -> 21.01 ($6176.00) after 0.5s @ dev
✔ PASS 3.28 -> 21.01 ($6216.50) ($91.64)
Linkswap: 100%
gas: 294761
SELL YFL->DPI 1.70 -> 1.06 ($510.52) after 0.2s @ dev
✔ PASS 1.70 -> 1.06 ($364.99) ($114.56)
Linkswap: 100%
gas: 360086
SELL DPI->YFL 4.18 -> 6.42 ($1891.69) after 0.7s @ dev
✔ PASS 4.18 -> 6.42 ($1813.58) ($116.31)
Linkswap: 100%
gas: 360245
```
```
BUY LINK->CRV 194.57 -> 1771.97 ($4926.08) after 1.0s @ dev
✔ PASS 194.57 -> 1771.97 ($6456.40) ($119.34)
Linkswap: 100%
gas: 388891
BUY CRV->LINK 112.81 -> 9.40 ($306.14) after 0.7s @ dev
✔ PASS 112.81 -> 9.40 ($431.77) ($118.16)
Linkswap: 100%
gas: 385068
``` …
> feat: Linkswap

- packages/asset-swapper/src/utils/market_operation_utils/comparison_price.ts
- packages/asset-swapper/src/utils/market_operation_utils/index.ts
- packages/asset-swapper/test/comparison_price_test.ts
Adust the comparison price calculation to include an overhead penalty.
Updated comparison price tests.
> add exchange proxy overhead penalty to comparison price

- packages/migrations/CHANGELOG.json
- packages/migrations/src/migration.ts
Sorry kim, constructor args both a) changed and b) had the wrong exchange version.
> fix: FQT in migrations

- docs/basics/allowances.rst
Update allowances docs to reflect new canonical allowance target.
> docs: update allowances blurb

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
These pools are broken because AAVE v1 doesn't have enough liquidity to cover the swaps.
- https://etherscan.io/address/0x79a8c46dea5ada233abaffd40f3a0a2b1e5a4f27
- https://etherscan.io/address/0x45f783cce6b7ff23b2ab2d70e416cdb7d6055f51
> AS: Drop Y and BUSD curve pools

- packages/asset-swapper/src/constants.ts
- packages/asset-swapper/src/swap_quoter.ts
- packages/asset-swapper/src/types.ts
Add the ability to blacklist specified `txOrigin`s from using RFQT.
> add tx origin blacklist to RFQ options

- contracts/zero-ex/contracts/src/features/PancakeSwapFeature.sol
> `@0x/contracts-zero-ex`: Fix `PancakeSwapFeature` sushi values

- docs/basics/functions.rst
> docs: Fix EIP712 hashing docs for limit and RFQ orders

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/comparison_price.ts
- packages/asset-swapper/test/comparison_price_test.ts
> use the RfqOrder source flag for comparison price EP overhead

- packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts
> Fix Multiplex multi-hop encoding issue

- packages/asset-swapper/package.json
- packages/asset-swapper/src/swap_quoter.ts
- packages/asset-swapper/src/types.ts
- packages/asset-swapper/src/utils/quote_requestor.ts
- packages/asset-swapper/test/quote_requestor_test.ts
- packages/asset-swapper/test/utils/test_helpers.ts
- yarn.lock
Contains a small amount of refactoring to make our existing code support both RFQT and RFQM flows. Unit tests have been updated and new coverage is added for RFQM flows.
> [MKR-3] Prepare Asset Swapper for RFQM

- contracts/zero-ex/CHANGELOG.json
- contracts/zero-ex/contracts/src/features/PancakeSwapFeature.sol
Which decided to remove an argument from their `swap()` function so the selector is different from everyone else.
> Fix PancakeSwapFeature BakerySwap swap selector

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/bridge_source_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/orders.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
- packages/asset-swapper/test/market_operation_utils_test.ts
> Add Kyber DMM as a liquidity source

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/liquidity_provider_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
> Adjust gas cost for LiquidityProvider sources that hop through WETH

- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
> [asset-swapper] add Native fee token on all chains

- packages/asset-swapper/test/market_operation_utils_test.ts
> Fix asset-swapper test

- packages/asset-swapper/src/utils/quote_requestor.ts
- packages/asset-swapper/test/quote_requestor_test.ts
Disables `isLastLook` parameter when not explicitly set.
> only set Last Look parameter if it's explicitly set

- docs/basics/protocol_fees.rst
> [docs] Remove 10 days from protocol fees docs [TKR-44]

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/quote_consumers/quote_consumer_utils.ts
- AS change: https://github.com/0xProject/0x-api/pull/552
> fix: feeType=positive_slippage logic [TKR-81]

- contracts/treasury/CHANGELOG.json
- contracts/treasury/contracts/src/IZrxTreasury.sol
- contracts/treasury/contracts/src/ZrxTreasury.sol
- contracts/treasury/test/treasury_test.ts
Fixes a bug in the treasury voting power logic and adds test. 
Also updates constructor to avoid deploying another DefaultPoolOperator contract. 
> Fix treasury voting power calculation

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
```
SELL USDC->LUSD 963323.22 -> 962764.82 ($963323.22) after 4.5s @ new
✔ PASS 963323.22 -> 962792.06 ($961333.05) ($50.44)
Uniswap_V2: 12%, Curve: 88%
gas: 647351
SELL LUSD->USDC 602272.21 -> 601008.83 ($601391.09) after 15.8s @ new
✔ PASS 602272.21 -> 601008.82 ($600974.99) ($33.82)
Curve: 100%
gas: 434096
```
> feat: Add LUSD Curve pool

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts
> fix: reactivate PancakeSwap, BakerySwap VIP on BSC

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
Closes https://github.com/0xProject/protocol/pull/224
^ Above is the PR with Balancer V2 and CurveETH support used for deployment.
> feat: Deployed Balancer V2 and Curve ETH support

- contracts/zero-ex/CHANGELOG.json
- contracts/zero-ex/contracts/src/transformers/bridges/BridgeAdapter.sol
- contracts/zero-ex/contracts/src/transformers/bridges/mixins/MixinCurve.sol
- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts
- packages/asset-swapper/src/utils/market_operation_utils/bridge_source_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
Disables Curve VIP when WETH is involved (as we need to withdraw it then trade)
```
SELL STETH->ETH 17.37 -> 17.24 ($58830.75) after 2.7s @ new
✔ PASS 17.37 -> 17.24 ($57700.02) ($62.26)
Curve: 100%
gas: 208784
SELL DAI->STETH 9850.60 -> 2.97 ($9877.88) after 3.3s @ new
✔ PASS 9850.60 -> 2.97 ($9928.93) ($123.67)
MultiHop: 100%
Balancer, Curve, intermediateToken: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2}
gas: 414740
```
> feat: Support ETH based Curve pools

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/index.ts
Observed collisions with PLP are above an acceptable amount. Thus PLP now creates a fallback in the event of an on-chain failure.
[Simbot](https://metabase.spaceship.0x.org/dashboard/186?run_id=jacob-mainnet-plp-fallback&adjusted_amount_bought_win_tolerance__bps_=1)
> Fix: PLP now generates a fallback

- packages/asset-swapper/src/index.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
> chore: Deploy FQT with UniswapV3 support

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/index.ts
- packages/asset-swapper/src/utils/market_operation_utils/pools_cache/balancer_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/pools_cache/balancer_v2_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/pools_cache/pools_cache.ts
Cache pools for 30mins, fetch them async if not fresh.
> feat: async balancer v2 pool cache

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts
> Add ETH pseudo-address when wrapping/unwrapping in Multiplex multihop

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/index.ts
- packages/asset-swapper/src/swap_quoter.ts
- packages/asset-swapper/src/types.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/index.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
- packages/asset-swapper/src/utils/quote_report_generator.ts
> fix: add separate priceComparisonsReport to fix missing quoteReport data [TKR-91]

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/swap_quoter.ts
- packages/asset-swapper/src/types.ts
> fix: Sampler contract address overrides

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/contracts/src/TwoHopSampler.sol
- packages/asset-swapper/contracts/src/UniswapV3Sampler.sol
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
`TwoHopSampler` needs to perform a `call` instead of a `staticcall`. The `amounts` need to be the last value returned by one of the sampler functions.
[Simbot](https://metabase.spaceship.0x.org/dashboard/186?run_id=jacob-fix-two-hop-sampler&adjusted_amount_bought_win_tolerance__bps_=0.5)
> fix: TwoHopSampler call

- packages/asset-swapper/package.json
- packages/asset-swapper/src/index.ts
- packages/asset-swapper/src/types.ts
- packages/asset-swapper/src/utils/alt_mm_implementation_utils.ts
- packages/asset-swapper/src/utils/quote_requestor.ts
- packages/asset-swapper/test/quote_requestor_test.ts
- yarn.lock
Adds the `fee` parameter to Quote Requestor.
> fix: Added fee parameter to Quote Requestor

- contracts/zero-ex/contracts/src/features/MultiplexFeature.sol
- packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts
- packages/asset-swapper/src/quote_consumers/quote_consumer_utils.ts
> Multiplex UniswapV3

- contracts/zero-ex/CHANGELOG.json
- contracts/zero-ex/test/features/selector_collision_test.ts
> Add special selectors to selector collision test

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
> Add Huobi Token to liquidity provider tokens

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
> chore: Temporarily disable a LiquidityProvider

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
Re-enable default Liquidity Provider
Update KNC token address
Enable PLP VIP on BSC
> Miscellaneous Liquidity Provider changes

- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
> chore: adding Uniswap v3 as a fee source

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/bridge_source_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/orders.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
- QUICK, TITAN, IRON as intermediate tokens
- WaultSwap (wault.finance)
- Polydex (polydex.fi)
- Polygon Curve renBTC (https://polygon.curve.fi/ren/)
> QUICK, TITAN, IRON as intermediate tokens, integrating WaultSwap, Polydex, Curve renBTC pool

- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/index.ts
- packages/asset-swapper/src/utils/market_operation_utils/path.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
- packages/asset-swapper/test/comparison_price_test.ts
- packages/asset-swapper/test/market_operation_utils_test.ts
- the power of 2 indexing was wrapping around and we started having duplicate SOURCE_FLAGS index
> fix: duplicate SOURCE_FLAGS index

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/pools_cache/balancer_v2_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/test/pools_cache_test.ts
> feat: Balancer V2 Polygon

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/path.ts
- packages/asset-swapper/test/path_test.ts
Fixes issue where PLP was considered a non-sturdy source, when a fallback was added PLP would be removed from the optimal path.
[Simbot](https://metabase.spaceship.0x.org/dashboard/186?run_id=jacob-polygon-plp-3&adjusted_amount_bought_win_tolerance__bps_=0.5)
> fix: PLP fallback

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/bridge_source_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/orders.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
> feat: ShibaSwap

- packages/asset-swapper/src/utils/quote_requestor.ts
For better visibility, emit a log when a request is returned between 99% and 100% of the requested amount.
> chore: emit a log when a quote is returned that is between 99-100% of request

- packages/asset-swapper/src/utils/quote_requestor.ts
> fix: uncaught type error while logging

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/bridge_source_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/orders.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
> feat: JetSwap

- contracts/erc20/contracts/src/v06/LibERC20TokenV06.sol
- contracts/treasury/contracts/src/DefaultPoolOperator.sol
- contracts/zero-ex/contracts/src/features/multiplex/MultiplexFeature.sol
- contracts/zero-ex/contracts/src/features/multiplex/MultiplexLiquidityProvider.sol
- contracts/zero-ex/contracts/src/features/multiplex/MultiplexUniswapV2.sol
> Address Multiplex V2 spot-check findings

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/bridge_source_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/orders.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
> feat: IronSwap

- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
> feat: Saddle alETH, D4 pools

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/bridge_source_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/orders.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
> feat: ACryptoS StableSwap

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
[Simbot with DSU](https://metabase.spaceship.0x.org/dashboard/186?run_id=jacob-curve-tripcrypto2&adjusted_amount_bought_win_tolerance__bps_=1.0)
[Simbot](https://metabase.spaceship.0x.org/dashboard/186?run_id=jacob-curve-tripcrypto2-2&adjusted_amount_bought_win_tolerance__bps_=1.0)
> feat: Curve tricrypto2 + ESD v2

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
- packages/contract-addresses/src/index.ts
- packages/migrations/CHANGELOG.json
- packages/migrations/src/migration.ts
> Add treasury address to contract-addresses

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/index.ts
- packages/asset-swapper/src/utils/market_operation_utils/path.ts
- packages/asset-swapper/test/market_operation_utils_test.ts
- packages/asset-swapper/test/path_test.ts
> fix: fallback path include unused fills on a used source

- contracts/zero-ex/CHANGELOG.json
- contracts/zero-ex/package.json
Add `ethers` as an explicit dependency of `0x/contracts-zero-ex`. See PR #305 for an detailed explanation of the problem this fixes.
> Add ethers as a dependency of `@0x/contracts-zero-ex`

- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
> add: Curve new pools (CVX-CRX, MIM, atricrypto3)

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
> add: Curve new pools (CVX-CRX, MIM, atricrypto3) - CHANGELOG

- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
> fix: UST spam by temporarily disabling

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/test/contracts/erc20_bridge_sampler_test.ts
- packages/asset-swapper/test/quote_simulation_test.ts
Remove protocol fees from AssetSwapper by setting `PROTOCOL_FEE_MULTIPLIER` to zero.
-   [x ] Prefix PR title with `[WIP]` if necessary.
> feat: remove protocol fees for V4 in AssetSwapper WIP

- docs/basics/protocol_fees.rst
> Update docs for zero protocol fees

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/package.json
- packages/asset-swapper/src/swap_quoter.ts
- packages/asset-swapper/src/types.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/fills.ts
- packages/asset-swapper/src/utils/market_operation_utils/index.ts
- packages/asset-swapper/src/utils/market_operation_utils/path.ts
- packages/asset-swapper/src/utils/market_operation_utils/path_optimizer.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
- packages/asset-swapper/test/market_operation_utils_test.ts
- yarn.lock
Initial integration of the new router with RFQ/Limit order support and basic VIP handling
> feat: initial integration of new router

- contracts/zero-ex/CHANGELOG.json
- contracts/zero-ex/contracts/src/migrations/FullMigration.sol
- contracts/zero-ex/src/migration.ts
- packages/contract-addresses/addresses.json
- packages/migrations/CHANGELOG.json
Add OtcOrder feature deployment to `fullMigrateAsync`
Not sure I understand how to update the addresses. In my local ganache, here are the new addresses:
```
FullMigration successfully deployed at 0xdd66c23e07b4d6925b6089b5fe6fc9e62941afe8
ZeroEx successfully deployed at 0x4609e0ed27a8baac57b753d36a5d2971915588f9
FeeCollectorController successfully deployed at 0x4ef5b1e3da5573466fb1724d2fca95290119b664
SimpleFunctionRegistryFeature successfully deployed at 0xd7e3593d3d8a22480e2136eab9497286d87c0231
OwnableFeature successfully deployed at 0x2579d2b186bba16999016db077b4874a7520f92e
TransformERC20Feature successfully deployed at 0x404c55a936f3006b13b020efaaf5771a600ec04d
MetaTransactionsFeature successfully deployed at 0xfd946d47d3db1e06126d16281fb3e222a1ba8179
NativeOrdersFeature …
```
> chore: add OtcOrder feature to fullMigrateAsync

- contracts/zero-ex/CHANGELOG.json
- contracts/zero-ex/contracts/src/features/MetaTransactionsFeature.sol
- contracts/zero-ex/contracts/test/TestMetaTransactionsTransformERC20Feature.sol
- contracts/zero-ex/test/features/meta_transactions_test.ts
Add a check to ensure mtxs do not cause the EP's ETH balance to go down.
> Add ETH leak modifier to mtx functions

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/contracts/src/UniswapV3Sampler.sol
[TKR-263]
Add support for UniswapV3 1bps pools, [example here of USDT/USDC](https://info.uniswap.org/#/pools/0x3416cf6c708da44db2624d63ea0aaef7113527c6).
[Simbot](https://metabase.spaceship.0x.org/dashboard/186?run_id=jacob-uniswapv3-1bps&adjusted_amount_bought_win_tolerance__bps_=1.0)
> feat: Uniswap V3 1bps pools [TKR-263]

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
Added very liquid pool [FEI-TRIBE](https://v2.info.uniswap.org/pair/0x9928e4046d7c6513326ccea028cd3e7a91c7590a) on UniV2. Helps users go ETH->TRIBE via ETH->FEI->TRIBE
Also added [OHM-FRAX](https://v2.info.uniswap.org/pair/0x2dce0dda1c2f98e0f171de8333c3c6fe1bbf4877) and [FXS-FRAX](https://v2.info.uniswap.org/pair/0xe1573b9d29e2183b1af0e743dc2754979a40d237)
> feat: Specify FEI/TRIBE liquid pool

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
Sushi Router address from the docs was initially incorrect.
Here is the correct address on celo `0x1421bde4b10e8dd459b3bcb598810b1337d56842`
> Sushi router celo fix

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/contracts/src/UtilitySampler.sol
- packages/asset-swapper/src/index.ts
- packages/asset-swapper/src/types.ts
- packages/asset-swapper/src/utils/market_operation_utils/index.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
- packages/asset-swapper/test/market_operation_utils_test.ts
Adds the ability to capture sampler metrics.
Currently defined to record the gas before operations (approx the gas limit) and gas after operations (gas we used for sampler calls).
> chore: Add ability to capture sampler metrics

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
Adds the Curve ETH/CRV pool, it's ok... expensive, uses different selectors (uint256 over int128)
[Simbot](https://metabase.spaceship.0x.org/dashboard/186?run_id=jacob-curve-ethcrv&adjusted_amount_bought_win_tolerance__bps_=1.0)
> chore: Curve added ETH/CRV pool

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/contracts/src/UniswapV3Sampler.sol
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
> feat: UniswapV3 on Polygon

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
https://docs.beethovenx.io/developers/subgraphs
> fix: Beethovenx graphql endpoint

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/package.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/index.ts
- packages/asset-swapper/src/utils/market_operation_utils/path_optimizer.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
- yarn.lock
> feat: Udate neon-router and use router estimated output amount

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/index.ts
- packages/asset-swapper/src/utils/market_operation_utils/path_optimizer.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
Allows for timing data to be collected around Routing
> feat: Capture Routing timing metrics

- packages/asset-swapper/src/utils/alt_mm_implementation_utils.ts
> fix: axios object dumping in logs

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
Adds the Optics Bridge v2 contract addresses as intermediate hops
> chore: Celo Update certain tokens since Optics v2

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/path_optimizer.ts
> fix: don't create fills for 0 output samples and negative adjusted rate orders

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
[Simbot](https://metabase.spaceship.0x.org/dashboard/186?run_id=jacob-curve-cvx-eth-1&adjusted_amount_bought_win_tolerance__bps_=1.0)
> chore: Enable Curve ETH/CVX

- contracts/zero-ex/contracts/src/features/ERC721OrdersFeature.sol
- contracts/zero-ex/contracts/src/features/interfaces/IERC721OrdersFeature.sol
- contracts/zero-ex/contracts/src/features/libs/LibERC721Order.sol
- contracts/zero-ex/contracts/src/fixins/FixinCommon.sol
- contracts/zero-ex/contracts/src/fixins/FixinERC721Spender.sol
- contracts/zero-ex/contracts/src/fixins/FixinTokenSpender.sol
- contracts/zero-ex/contracts/src/vendor/IFeeRecipient.sol
- contracts/zero-ex/contracts/test/TestERC721OrderPresigner.sol
- contracts/zero-ex/contracts/test/TestFeeRecipient.sol
- contracts/zero-ex/test/features/erc721_orders_test.ts
> address feedback from original PR

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
> chore: Use MIM on Fantom as an intermediary asset

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/swap_quoter.ts
> fix: worstCaseQuoteInfo calculating buys incorrectly [TKR-296]

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/package.json
- packages/asset-swapper/src/utils/market_operation_utils/path_optimizer.ts
- yarn.lock
> fix: incorrect output scaling when input is less than desired amount

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/contracts/src/UniswapV3Sampler.sol
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/orders.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
> feat: Improve Uniswap V3 gas schedule

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/path_optimizer.ts
> fix: router RFQ underutilization

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/contracts/src/UniswapV3Sampler.sol
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/orders.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
This reverts code changes from commit 84e4819e6ed4615e880699b936e3835b4bd2e2b4 due to an issue discovered with buys
> fix: Revert Improve Uniswap V3 gas schedule (#397)

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/path_optimizer.ts
> fix: 1 base unit output amount being scale down, rounding to 0 output

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
> fix: added ohmv2/btrfly pair for better routing on sushiswap and univ3

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/package.json
- packages/asset-swapper/src/utils/market_operation_utils/fills.ts
- packages/asset-swapper/src/utils/market_operation_utils/path_optimizer.ts
- yarn.lock
> fix: start native orders "samples" at 0 & don't skip neg adj orders

- contracts/zero-ex/contracts/src/errors/LibNFTOrdersRichErrors.sol
- contracts/zero-ex/contracts/src/features/ERC165Feature.sol
- contracts/zero-ex/contracts/src/features/interfaces/IERC1155OrdersFeature.sol
- contracts/zero-ex/contracts/src/features/interfaces/IERC165Feature.sol
- contracts/zero-ex/contracts/src/features/interfaces/IERC721OrdersFeature.sol
- contracts/zero-ex/contracts/src/features/libs/LibNFTOrder.sol
- contracts/zero-ex/contracts/src/features/nft_orders/ERC1155OrdersFeature.sol
- contracts/zero-ex/contracts/src/features/nft_orders/ERC721OrdersFeature.sol
- contracts/zero-ex/contracts/src/features/nft_orders/NFTOrders.sol
- contracts/zero-ex/contracts/src/fixins/FixinERC1155Spender.sol
- contracts/zero-ex/contracts/src/fixins/FixinERC721Spender.sol
- contracts/zero-ex/contracts/src/storage/LibERC1155OrdersStorage.sol
- contracts/zero-ex/contracts/src/storage/LibERC721OrdersStorage.sol
- contracts/zero-ex/contracts/src/storage/LibStorage.sol
- contracts/zero-ex/contracts/src/vendor/IERC1155Token.sol
- contracts/zero-ex/contracts/src/vendor/IERC721Token.sol
- contracts/zero-ex/contracts/src/vendor/IFeeRecipient.sol
- contracts/zero-ex/contracts/src/vendor/IPropertyValidator.sol
- contracts/zero-ex/contracts/src/vendor/ITakerCallback.sol
- contracts/zero-ex/contracts/test/TestNFTOrderPresigner.sol
- contracts/zero-ex/test/features/erc1155_orders_test.ts
- contracts/zero-ex/test/features/erc721_orders_test.ts
> NFT orders: address audit findings

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/package.json
- packages/asset-swapper/src/utils/market_operation_utils/path_optimizer.ts
- yarn.lock
> fix: native order scaling & don't try to route 1 wei trades (it will fail)

- .circleci/config.yml
- package.json
- yarn.lock
> chore: update Node16

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/contracts/src/UniswapV3Sampler.sol
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/geist_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/orders.ts
- packages/asset-swapper/src/utils/market_operation_utils/path_optimizer.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
- packages/contract-addresses/CHANGELOG.json
> feat: Improve Uniswap V3 gas schedule redux

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/contracts/src/UniswapV3Sampler.sol
900k gas allowance was a bit too high, pushing us up near production limits, 700k should be a sufficient bump
> fix: lower UniswapV3Sampler quote gas allowance to 700k

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
Think we're possibly using an old Uniswap_V3 Router version on Ropsten. Updated to latest [found in the docs](https://docs.uniswap.org/protocol/reference/deployments) and it's consistent with what we use on other networks.
https://ropsten.api.0x.org/swap/v1/quote?buyToken=0x07865c6e87b9f70255377e024ace6630c1eaa37f&sellToken=ETH&sellAmount=1507099614911829913&takerAddress=0x24420bC8C760787F3eEF3b809e81f44d31a9c5A2
```json
{
"code": 105,
"reason": "WalletExecuteDelegateCallFailedError",
"values": {
"wallet": "0x22f9dcf4647084d6c31b2765f6910cd85c178c18",
"callTarget": "0xeca4b22f9005cd610c6a09e91fc3dd298a64837d",
"callData": "0x832b24bb000000000000000000000000000000000000000000000000000000000000002000000000000000000000000024420bc8c760787f3eef3b809e81f44d31a9c5a200000000000000000000000024420bc …
```
> fix: Update Ropsten UniswapV3 Router address

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
> feat: Curve YFI-ETH

- .circleci/config.yml
- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/path_optimizer.ts
- packages/asset-swapper/test/market_operation_utils_test.ts
This enables using the neon-router on CircleCI and skips tests that are not supported by the router
> feat: use neon-router in CI tests

- .github/workflows/publish.yml
> fix: use Node 16 for publish GH action

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts
> add real VIP support for eligible RFQT swaps

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts
The code path for RFQT in quote consumer was not checking if the swap requires TransformERC20.
> AS: Fix RFQT VIP quote consumer

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/quote_report_generator.ts
> Add estimatedGas to ExtendedQuoteReport

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
Add cvxFXS/FXS curve pool on mainnet.
Test run on simbot (id: `cvxfxs-curve`)
New feature (non-breaking change which adds functionality) 
> Add cvxfxs-fxs curve pool on Ethereum mainnet

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/quote_report_generator.ts
The quote report considered sources where incorrectly filtered out when doing a Sell. This PR fixes the bug
> Fix the filter for considered sources on indicative sells for Quote Report

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/swap_quoter.ts
> add message to changelog for #467

- .gitignore
- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
Remove two outdated saddle pools:
* stables(Stablecoin): 0x3911f80530595fbd01ab1516ab61255d75aeb066
* bitcoins(BTC): 0x4f6a43ad7cba042606decaca730d4ce0a57ac62e
Add two new V2 pools:
* stablesV2: 0xaCb83E0633d6605c5001e2Ab59EF3C745547C8C7
* bitcoinsV2: 0xdf3309771d2BF82cb2B6C56F9f5365C8bD97c4f2
> Update saddle mainnet pools

- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
> Fix a lint issue

- contracts/zero-ex/CHANGELOG.json
- contracts/zero-ex/contracts/src/transformers/bridges/mixins/MixinLido.sol
- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/contracts/src/LidoSampler.sol
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/orders.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
Add stETH wrap/unwrap support
* New feature (non-breaking change which adds functionality) 
> Add stETH wrap/unwrap support [TKR-377]

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/bridge_source_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/orders.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
* New feature (non-breaking change which adds functionality) 
> feat/add MeshSwap on Polygon [TKR-374]

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/quote_report_generator.ts
Filter out empty (no liquidity on source) Quote Report entries
* New feature (non-breaking change which adds functionality)
-   [X] Prefix PR title with `[WIP]` if necessary.
-   [X] Update documentation as needed.
-   [X] Add new entries to the relevant CHANGELOG.jsons.
> Chore: Do not send empty entries on Quote Report

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts
- packages/asset-swapper/src/utils/market_operation_utils/bridge_source_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/orders.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
Offboard/Cleanup Jetswap, CafeSwap, SwapLiquidity, Degenhaus, and Polydex
cleanup
> Offboard Jetswap, CafeSwap, JulSwap, and PolyDex

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
> Update Ethereum and Optimism FQT addresses

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
Remove nUSD from intermediate liquidity to save on sampler gas
Simbot Polygon
> Remove nUSD from intermediate liquidity to save on sampler gas

- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
> Fix typos in GMX sampling logic

- contracts/zero-ex/contracts/src/transformers/bridges/EthereumBridgeAdapter.sol
- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
> Remove Mooniswap on Ethereum Mainnet

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
> Update FQT addresses on mainnet and Optimism [TKR-324]

- packages/asset-swapper/src/utils/market_operation_utils/index.ts
- packages/asset-swapper/src/utils/market_operation_utils/pools_cache/balancer_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/pools_cache/balancer_v2_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/pools_cache/cream_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/pools_cache/pools_cache.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/test/market_operation_utils_test.ts
- packages/asset-swapper/test/pools_cache_test.ts
* Make `_refreshPoolCacheIfRequiredAsync` type-safe by using `_.values` (`cache` was `any`). 
* Use `Map` instead of object in `PoolsCache`
* Refactor `PoolsCache` and simplify its public interface.
* NOTE: #519 should be merged first. 
> Refactor PoolsCache (part 1) [TKR-500]

- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/pools_cache/balancer_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/pools_cache/balancer_v2_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/pools_cache/cream_utils.ts
- packages/asset-swapper/src/utils/market_operation_utils/pools_cache/index.ts
- packages/asset-swapper/src/utils/market_operation_utils/pools_cache/no_op_pools_cache.ts
- packages/asset-swapper/src/utils/market_operation_utils/pools_cache/pools_cache.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/test/market_operation_utils_test.ts
- packages/asset-swapper/test/pools_cache_test.ts
* Implement `NoOpPoolsCache` that can be used as a placeholder implementation
* Use `NoOpPoolsCache` on instead of the real implementation on chains so that resource isn't unnecessarily wasted (some pool updates can be quite compute intensive).
> Refactor PoolsCache (part 2) [TKR-500] 

- packages/asset-swapper/src/index.ts
- packages/asset-swapper/src/swap_quoter.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
* Delete `getBidAskLiquidityForMakerTakerAssetPairAsync` as it's not used anymore.
-   [ ] Add new entries to the relevant CHANGELOG.jsons. (will be done before the PR is merged to avoid a merge conflict)
> Remove market liquidity depth related logic and types [TKR-484]

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/package.json
- yarn.lock
> chore: Upgrade `fast-abi`

- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
> chore: Clean up Mirror and UST related stuff [TKR-465]

- packages/contract-addresses/addresses.json
* Revert Ganache (1337) FQT address as it was mistakenly updated.
* Update Polygon (137) FQT address with the new one.
> fix: Fix Polygon and Ganache FillQuoteTransformer addresses

- .circleci/config.yml
- packages/contract-addresses/package.json
- packages/contract-addresses/test/addresses_test.ts
- packages/contract-addresses/tsconfig.json
- yarn.lock
> chore: Add checks for `addresses.json` [TKR-519]

- packages/asset-swapper/CHANGELOG.json
- packages/asset-swapper/src/utils/market_operation_utils/constants.ts
- packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
- packages/asset-swapper/src/utils/market_operation_utils/types.ts
change WooFi gas estimates on other chains
ran simbot
Bug fix (non-breaking change which fixes an issue
> WooFi Gas Estimates

- packages/asset-swapper/README.md
> chore: Fix asset-swapper deprecation notice

- contracts/zero-ex/CHANGELOG.json
- contracts/zero-ex/contracts/src/transformers/FillQuoteTransformer.sol
- packages/protocol-utils/CHANGELOG.json
- packages/protocol-utils/src/transformer_utils.ts
> prereq code for otc orders in asset-swapper

- contracts/zero-ex/CHANGELOG.json
- contracts/zero-ex/test/transformers/fill_quote_transformer_test.ts
- packages/protocol-utils/src/transformer_utils.ts
> added otc order array to createTranformData

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
> nwe fqt address and changelog

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
> feat: add new fqt for optimism with balancerv2

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
> feat: add new fqt address containing nerve mixin

- packages/protocol-utils/src/nft_orders.ts
- packages/protocol-utils/src/revert-errors/native_orders.ts
- packages/protocol-utils/src/revert-errors/nft_orders.ts
- packages/protocol-utils/src/transformer_utils.ts
> [protocol-utils] Purge tslint comments

- .prettierignore
- contracts/erc20/src/artifacts.ts
- contracts/erc20/test/artifacts.ts
- contracts/test-utils/src/mocha_blockchain.ts
- contracts/test-utils/src/number_utils.ts
- contracts/test-utils/src/order_utils.ts
- contracts/test-utils/test/mocha_blockchain.ts
- contracts/test-utils/test/order_hash_test.ts
- contracts/utils/test/lib_bytes.ts
- contracts/zero-ex/test/artifacts.ts
- contracts/zero-ex/test/features/native_orders_feature_test.ts
- contracts/zero-ex/test/features/otc_orders_test.ts
- contracts/zero-ex/test/transformers/fill_quote_transformer_test.ts
- contracts/zero-ex/test/utils/orders.ts
- package.json
- packages/protocol-utils/src/orders.ts
- yarn.lock
> Upgrade Prettier

- .circleci/config.yml
> fix: Remove branch-specific Circle CI cache [TKR-608]

- contracts/zero-ex/foundry.toml
> chore: Update `forge-std` and fix `foundry.toml`

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
- packages/contract-addresses/src/index.ts
- packages/contract-addresses/test/addresses_test.ts
> chore: Remove Ropsten/Rinkeby from `@0x/contract-addresses` [TKR-603]

- contracts/erc20/package.json
- contracts/treasury/package.json
- contracts/utils/package.json
- contracts/zero-ex/package.json
- yarn.lock
> chore: Upgrade `@0x/contracts-gen` [TKR-610]

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
> Enable RFQT v2 on Mainnet

- contracts/zero-ex/contracts/src/transformers/bridges/FantomBridgeAdapter.sol
> add BalancerV2 Batch support for Fantom Bridge Adapter [TKR-630]

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
> feat: Add `BalancerV2Batch` support in Fantom `FillQuoteTransformer` [TKR-630]

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
> added new RFQTV2 compliant fqt

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
> feat: Update Polygon FillQuoteTransformer to support Solidly (and its forks) [TKR-460]

- CONTRIBUTING.md
- PULL_REQUEST_TEMPLATE.md
Closes https://linear.app/0xproject/issue/GOV-4/switch-from-using-wip-for-prs-to-github-drafts
> Switch contributor instructions to use github draft mode for PRs

- docs/architecture/proxy.rst
Closes https://github.com/0xProject/protocol/issues/485
> Fixes the owner function documentation

- contracts/zero-ex/scripts/rollback.ts
Update the subgraph URL. Don't re-register `owner()`.
> chore: Update rollback script

- docs/architecture/governor.rst
Update governor.rst to reflect accurate timelock durations.
Documentation update
> Update timelock days

- contracts/zero-ex/contracts/src/transformers/bridges/mixins/MixinWOOFi.sol
Migrating our WooFi mixin to V2 of the protocol. 
> feat: WooFi V2 [LIT-755]

- contracts/zero-ex/compiler.json
> chore: fix compiler to read in arbitrum bridge adapter [LIT-794]

- packages/contract-addresses/addresses.json
> chore: update contract-addresses with new bridge adapters with Woofi enabled [LIT-774]

- contracts/zero-ex/contracts/src/transformers/bridges/ArbitrumBridgeAdapter.sol
- contracts/zero-ex/contracts/src/transformers/bridges/OptimismBridgeAdapter.sol
- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
Add Woofi to Arbitrum and Optimism bridge adapters(they were already deployed, but these changes weren't merged into this repo). Additionally, the new FQT address for Arbitrum wasn't updated
> chore: Add woofi to Arbitrum & Optimism bridge adapters [LIT-774]

- contracts/zero-ex/tests/transformers/AffiliateFeeTransformerTest.t.sol
- contracts/zero-ex/tests/transformers/PositiveSlippageFeeTransformerTest.t.sol
Fix forge build which started failing after the merge of https://github.com/0xProject/protocol/pull/650
> Fix path to foundry base test

- contracts/zero-ex/CHANGELOG.json
Update changelog for adding Kyber Elastic mixin.
> chore: update changelog for adding Kyber Elastic mixin

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
> chore: update FQT addresses for kyber elastic on mainnet and polygon

- contracts/zero-ex/CHANGELOG.json
- contracts/zero-ex/contracts/src/transformers/bridges/BSCBridgeAdapter.sol
- contracts/zero-ex/contracts/src/transformers/bridges/OptimismBridgeAdapter.sol
- contracts/zero-ex/tests/forked/SwapERC20ForERC20Test.t.sol
Add Kyber Elastic mixins for BSC and Optimism.
Forge tested the new mixins.
> feat:Add Kyber Elastic mixins

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
> chore: update addresses to reflect AaveV3 L2 encoding removal and KyberElastic Addition

- contracts/governance/src/CallWithGas.sol
- contracts/governance/src/IZeroExVotes.sol
- contracts/governance/src/ZRXWrappedToken.sol
- contracts/governance/src/ZeroExVotes.sol
- contracts/governance/test/ZeroExVotesMalicious.sol
- contracts/governance/test/ZeroExVotesTest.t.sol
> Prevent griefing by a malicious ZeroExVotes upgrade

- .gitignore
- contracts/zero-ex/CHANGELOG.json
- contracts/zero-ex/contracts/src/transformers/bridges/BridgeProtocols.sol
- contracts/zero-ex/contracts/src/transformers/bridges/EthereumBridgeAdapter.sol
- contracts/zero-ex/contracts/src/transformers/bridges/mixins/MixinBarter.sol
- packages/protocol-utils/CHANGELOG.json
- packages/protocol-utils/src/transformer_utils.ts
* Add Barter support in `EthereumBridgeAdapter`
* New feature (non-breaking change which adds functionality) 
> feat: Add Barter support to EthereumBridgeAdapter [LIT-981]

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
* Updated Ethereum FillQuoteTransformer address (deployed #703)
> feat: Update Ethereum FillQuoteTransformer address [LIT-981]

- contracts/erc20/CHANGELOG.json
- contracts/erc20/CHANGELOG.md
- contracts/erc20/package.json
- contracts/test-utils/CHANGELOG.json
- contracts/test-utils/CHANGELOG.md
- contracts/test-utils/package.json
- contracts/treasury/CHANGELOG.json
- contracts/treasury/CHANGELOG.md
- contracts/treasury/package.json
- contracts/utils/CHANGELOG.json
- contracts/utils/CHANGELOG.md
- contracts/utils/package.json
- contracts/zero-ex/CHANGELOG.json
- contracts/zero-ex/CHANGELOG.md
- contracts/zero-ex/package.json
- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/CHANGELOG.md
- packages/contract-addresses/package.json
- packages/contract-wrappers/CHANGELOG.json
- packages/contract-wrappers/CHANGELOG.md
- packages/contract-wrappers/package.json
- packages/protocol-utils/CHANGELOG.json
- packages/protocol-utils/CHANGELOG.md
- packages/protocol-utils/package.json
* Reverting
* 2b13dcfc1 Publish
* d2bea4aa4 Updated CHANGELOGS & MD docs
> fix: Revert changelog commits from previous failed publish

- contracts/zero-ex/CHANGELOG.json
- packages/contract-addresses/CHANGELOG.json
- packages/protocol-utils/CHANGELOG.json
github publish action updated changelog.json, changelog.md and git tags without publishing actual npm packages. 
As it's difficult to get this right (remove all relevant git tags, revert changelogs), bump up package versions instead.
> fix: Bump package versions to make publish action to work

- docs/index.rst
- docs/requirements.txt
Update Jinja dependency in attempt to fix ReadTheDocs build issue following this disscussion: https://github.com/readthedocs/readthedocs.org/issues/9038
* Bug fix (non-breaking change which fixes an issue)
> pin jinja dependency to try to fix read the doc build issues. fix minor typo

- docs/index.rst
Minor stylistic edits (increase logo size, bullet list format)
> minor stylistic edits

- contracts/zero-ex/CHANGELOG.json
- packages/contract-addresses/CHANGELOG.json
- packages/protocol-utils/CHANGELOG.json
> fix: Remove Timestamps from Trader Joe V2 CHANGELOG Entries

- docs/basics/orders.rst
Updated link to point to correct instance of 0x Orderbook API documentation.
-   [x ] Update documentation as needed.
> update old link

- docs/guides/nft_guide.rst
Added necessary whitespace for code blocks to properly render
> Fix code block rendering

- packages/contract-addresses/CHANGELOG.json
Previously merged commit contained invalid json for CHANGELOG.json belonging to the contract-addresses package. This PR fixes the CHANGELOG to allow for protocol package publishing.
* Bug fix (non-breaking change which fixes an issue)
> Fixing invalid CHANGELOG.json for contract-addresses

- contracts/zero-ex/tests/transformers/bridges/AvalancheBridgeAdapterTest.t.sol
- contracts/zero-ex/tests/transformers/bridges/BSCBridgeAdapterTest.t.sol
Check UniswapV3 support on Avalanche and BSC BridgeAdapters
> Check UniswapV3 support on Avalanche and BSC BridgeAdapters

- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
* Fixes LIT-1178
* Update Base FillQuoteTransformer address 
* Add Uniswap V3 Router V2 support
* New feature (non-breaking change which adds functionality)
> Update Base FillQuoteTransformer address

- contracts/zero-ex/CHANGELOG.json
- contracts/zero-ex/contracts/src/transformers/bridges/BaseBridgeAdapter.sol
- contracts/zero-ex/tests/transformers/bridges/BaseBridgeAdapterTest.t.sol
- packages/contract-addresses/CHANGELOG.json
- packages/contract-addresses/addresses.json
* Fixes LIT-1235
* Add Velodrome V2 support on Base
> Add Velodrome V2 support on Base
