0xProject/protocol

contracts/integrations/package.json, yarn.lock
Change contracts/integrations/package.json to refer to the LOCAL asset-swapper, not a gitpkg one, since asset-swapper does live in this same repo now.
=> Change contracts/integrations to use LOCAL asset-swapper

contracts/zero-ex/CHANGELOG.json, contracts/zero-ex/contracts/src/IZeroEx.sol, contracts/zero-ex/contracts/src/ZeroEx.sol, contracts/zero-ex/contracts/src/features/ISimpleFunctionRegistryFeature.sol, contracts/zero-ex/contracts/src/features/SimpleFunctionRegistryFeature.sol, contracts/zero-ex/contracts/test/TestInitialMigration.sol, contracts/zero-ex/test/features/simple_function_registry_test.ts, contracts/zero-ex/test/full_migration_test.ts, contracts/zero-ex/test/zero_ex_test.ts
This is a Yul rewrite of the `ZeroEx` contract. This saves about 1,000 gas as compared to the Solidity implementation.
The function `getFunctionImplementation(bytes4)` has been moved out into `SimpleFunctionRegistryFeature`.
From `contracts/zero-ex`, `yarn build && yarn test`.
There are no new tests. No functionality should change from the previous implementation except the removal of `getFunctionImplementation(bytes4)`.
* Gas golfing
-   [X] Add tests to cover changes as needed.
-   [X] Update documentation as needed.
=> rewrite ZeroEx in Yul

contracts/zero-ex/CHANGELOG.json, contracts/zero-ex/contracts/src/features/LiquidityProviderFeature.sol, contracts/zero-ex/contracts/src/features/MetaTransactionsFeature.sol, contracts/zero-ex/contracts/src/features/NativeOrdersFeature.sol, contracts/zero-ex/contracts/src/features/TransformERC20Feature.sol, contracts/zero-ex/contracts/src/features/libs/LibTokenSpender.sol, contracts/zero-ex/contracts/test/TestLibTokenSpender.sol, contracts/zero-ex/test/features/liquidity_provider_test.ts
And make use of the new flag in LiquidityProviderFeature, TransformERC20Feature, and MetaTransactionsFeature
=> Add checkAllowance flag to LibTokenSpender.spendERC20Tokens

contracts/integrations/test/exchange-proxy/mtx_test.ts, contracts/zero-ex/CHANGELOG.json, contracts/zero-ex/contracts/src/features/IMetaTransactionsFeature.sol, contracts/zero-ex/contracts/src/features/MetaTransactionsFeature.sol, contracts/zero-ex/contracts/test/TestMetaTransactionsTransformERC20Feature.sol, contracts/zero-ex/test/features/meta_transactions_test.ts, contracts/zero-ex/test/full_migration_test.ts
Convert `MetaTransactionsFeature` to use the new `LibSignature`
`yarn build && yarn test` from `contracts/zero-ex`
* non-breaking change to use `LibSignature` instead of the signature validation feature
-   [X] Prefix PR title with `[WIP]` if necessary.
-   [X] Add tests to cover changes as needed.
-   [X] Update documentation as needed.
=> Convert MetaTransactionsFeature to use the new LibSignature

contracts/zero-ex/CHANGELOG.json, contracts/zero-ex/contracts/src/features/TransformERC20Feature.sol, contracts/zero-ex/contracts/test/TestMintTokenERC20Transformer.sol, contracts/zero-ex/test/features/transform_erc20_test.ts
In the `TransformERC20Feature`, when `inputTokenAmount == uint256(-1)`, we interpret this as trying to sell the taker's *entire* available balance. But we did not check if the input token was ETH. This causes reverts because `0xeeeee...` is not a token. Now we just set `inputTokenAmount = msg.value` when ETH is being sold and `inputTokenAmount == uint256(-1)`.
=> TransformERC20: Fix selling entire ETH balance

contracts/zero-ex/CHANGELOG.json, contracts/zero-ex/contracts/src/features/INativeOrdersFeature.sol, contracts/zero-ex/contracts/src/features/NativeOrdersFeature.sol, contracts/zero-ex/contracts/src/features/libs/LibNativeOrder.sol, contracts/zero-ex/contracts/test/TestMetaTransactionsNativeOrdersFeature.sol, contracts/zero-ex/src/orders.ts, contracts/zero-ex/test/features/meta_transactions_test.ts, contracts/zero-ex/test/features/native_orders_feature_test.ts, docs/basics/orders.rst
- We no longer take a protocol fee on RFQ orders.
- RFQ orders now have a `taker` field.
=> Remove protocol fees from RFQ orders

contracts/zero-ex/CHANGELOG.json, contracts/zero-ex/contracts/src/features/NativeOrdersFeature.sol, contracts/zero-ex/test/features/native_orders_feature_test.ts
`getRfqOrderInfo()` now returns a status of INVALID for an order that has `txOrigin == 0`.
`yarn test`
* Bug fix
=> RFQ order with 0 txOrigin is INVALID

contracts/zero-ex/contracts/src/features/INativeOrdersFeature.sol, contracts/zero-ex/contracts/src/features/NativeOrdersFeature.sol, contracts/zero-ex/test/features/native_orders_feature_test.ts
Right now we have a single `PairOrdersCancelled` event, which is emitted when cancelling a pair for Limit or Market orders. In this PR we split this event into `PairCancelledLimitOrders` and `PairCancelledRfqOrders` so that a listener will know which order type the market was cancelled under, without having to dig into the calldata.
=> Splits `PairOrdersCancelled` event into Limit/RFQ

packages/asset-swapper/src/constants.ts, packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts, packages/asset-swapper/src/types.ts, packages/asset-swapper/test/exchange_proxy_swap_quote_consumer_test.ts
Allow the caller to specify `shouldSellEntireBalance` to make use of EP `-1`, indicating the amount to be transferred and sold is the entire max balance/allowance of the caller.
Needed for scenarios where the amount can be undeterministic, such as in the middle of an CFL operation.
[Sim - Enabled shouldSellEntireBalance](https://metabase.spaceship.0x.org/dashboard/139?run_id=dev-sell-all-enabled&adjusted_amount_bought_win_tolerance__bps_=0.5)
=> feat: [asset-swapper] support selling entire balance

packages/asset-swapper/src/index.ts, packages/asset-swapper/src/quote_consumers/utils.ts, packages/asset-swapper/src/types.ts, packages/asset-swapper/src/utils/market_operation_utils/index.ts, packages/asset-swapper/src/utils/market_operation_utils/path_optimizer.ts, packages/asset-swapper/src/utils/market_operation_utils/types.ts, packages/asset-swapper/src/utils/swap_quote_calculator.ts, packages/asset-swapper/test/utils/swap_quote.ts
Supports new feature: calculating user savings.
Blocks: https://github.com/0xProject/0x-api/pull/435
This PR adds new fields `unoptimizedQuoteInfo` and `unoptimizedOrders` to the SwapQuote. 
These new fields represent the best rate available from a single source, which would be the best alternative to our multi-source optimized path. 
=> Return unoptimized quote in SwapQuote

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/src/types.ts, packages/asset-swapper/src/utils/market_operation_utils/index.ts, packages/asset-swapper/src/utils/market_operation_utils/types.ts, packages/asset-swapper/src/utils/swap_quote_calculator.ts, packages/asset-swapper/test/utils/swap_quote.ts
Adds `takerAssetToEthRate` and `makerAssetToEthRate` to the swap quote response object, to be able to determine the ETH value of these assets for any quoted pair.
**NOTE:** Rates can sometimes be missing, in those cases a rate of `0` will be returned.
=> feat: add takerAssetToEthRate and makerAssetToEthRate  to quote response

packages/asset-swapper/src/utils/market_operation_utils/index.ts
Quote Reports are not being updated with RFQ information that is being acquired after the initial optimizer is run. This means that RFQ indicative and firm quotes are not properly being reported in the Quote Reporter at times.
I also refactored the function `_computeQuoteReport` to not pass in `nativeOrders`, because this field of information is already present in `marketSideLiquidity`
=> fix: Fix quote report

contracts/zero-ex/CHANGELOG.json, contracts/zero-ex/contracts/src/external/LiquidityProviderSandbox.sol, contracts/zero-ex/contracts/src/transformers/bridges/mixins/MixinZeroExBridge.sol, contracts/zero-ex/test/features/liquidity_provider_test.ts
All PLPs are now using the new interface. Removes backwards compatibility from `MixinZeroExBridge` and `LiquidityProviderSandbox`. This also fixes the issue of `LiquidityProviderSandbox` swallowing errors.
=> Remove PLP backwards-compatibility

contracts/zero-ex/CHANGELOG.json, contracts/zero-ex/contracts/src/transformers/bridges/BridgeAdapter.sol, contracts/zero-ex/contracts/src/transformers/bridges/mixins/MixinCryptoCom.sol
Bad constructor initialiser, using the BridgeAddress as the router address :\.
Modified to use the encoded bridgeData which contains the Router address.
```
SELL WETH->WBTC 124.46 -> 3.24 ($78920.14) after NaNs @ prod
✔ PASS 124.46 -> 3.24 ($77249.28) ($15.04)
CryptoCom: 100%
gas: 272873
```
=> fix: CryptoCom rollup

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts
Fixes bug where `fillAmount` was being incorrectly encoded with `uint(-1)`. For buys this is problematic as it attempts to perform partial math on the `uint(-1)` amount and results in a `UInt256BinOpError`, even if it it didn't it would revert as it didn't buy `uint(-1)`
=> fix: [asset-swapper] Encoded Buy fillAmount

contracts/erc20/CHANGELOG.json, contracts/erc20/contracts/src/v06/LibERC20TokenV06.sol, contracts/utils/CHANGELOG.json, contracts/utils/contracts/src/v06/LibSafeMathV06.sol, contracts/utils/contracts/src/v06/errors/LibSafeMathRichErrorsV06.sol, contracts/zero-ex/CHANGELOG.json, contracts/zero-ex/contracts/src/features/INativeOrdersFeature.sol, contracts/zero-ex/contracts/src/features/NativeOrdersFeature.sol, contracts/zero-ex/test/features/native_orders_feature_test.ts, packages/contract-artifacts/CHANGELOG.json, packages/contract-artifacts/artifacts/IZeroEx.json, packages/contract-wrappers/CHANGELOG.json, packages/contract-wrappers/src/generated-wrappers/i_zero_ex.ts
Adds the following `DevUtils`-equivalent functions to `NativeOrdersFeature` in the EP:
- `getLimitOrderRelevantState()`
- `getRfqOrderRelevantState()`
- `batchGetLimitOrderRelevantStates()`
- `batchGetRfqOrderRelevantStates()`
Also updated the return data size checks in `LibERC20TokenV06` to allow for tokens that return >= 32 bytes.
=> That time DevUtils wouldn't die

contracts/zero-ex/CHANGELOG.json, contracts/zero-ex/contracts/src/features/INativeOrdersFeature.sol, contracts/zero-ex/contracts/src/features/NativeOrdersFeature.sol, contracts/zero-ex/contracts/src/features/libs/LibNativeOrder.sol, contracts/zero-ex/test/features/native_orders_feature_test.ts
`getXOrderRelevantState()` can revert for a number of reasons (math ops, invalid tokens, etc), and therefore so do the batch versions. Mesh needs a batch function that is hardier.
This amends `batchGetLimitOrderRelevantState()` and `batchGetLimitOrderRelevantState()` to use `try this... catch` semantics to swallow reverts and return empty results for failing orders.
=> EP: Swallow reverts in `batchGetLimit/RfqRelevantStates()`

packages/protocol-utils/CHANGELOG.json, packages/protocol-utils/src/signature_utils.ts
Because `Web3Wrapper.signTypedDataV4Async()` will be removed by https://github.com/0xProject/tools/pull/21
=> `@0x/protocol-utils`: Use `Web3Wrapper.signTypedDataAsync()`

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/contracts/src/UniswapSampler.sol
The price on Uni v1 BNB/ETH is really good right now but it's a poisoned pool. The BNB token is partially broken such that the pool can receive BNB liquidity but can never remove it. So the price can only ever improve but will always fail if someone tries to buy BNB from it.
This special cases the token in the sampler so quoting X->BNB on uni v1 will always return 0.
=> AS: special case BNB in uni v1 sampler

contracts/zero-ex/CHANGELOG.json, contracts/zero-ex/contracts/src/transformers/FillQuoteTransformer.sol, packages/contract-addresses/CHANGELOG.json, packages/contract-addresses/addresses.json
- Update *future* FQT address.
- Remove the gas limit on ETH refund in FQT so we can potentially account for it in simbot when limit orders are involved. Still won't work though because I don't think we actually set `refundReceiver` in API right now, but one day :roll_eyes:.
=> FQT deploy + no gas limit ETH refund

contracts/treasury/CHANGELOG.json, contracts/treasury/contracts/src/IZrxTreasury.sol, contracts/treasury/contracts/src/ZrxTreasury.sol, contracts/treasury/test/treasury_test.ts
Changes `proposalThreshold` and `quorumThreshold` from immutables to state variables than can be updated via the new `updateThresholds` function. The `updateThresholds` function can only be called by the Treasury itself, so an update would need to be encoded in a proposal. 
=> Make the proposal/quorum thresholds updatable

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/src/constants.ts, packages/asset-swapper/src/index.ts, packages/asset-swapper/src/swap_quoter.ts, packages/asset-swapper/src/types.ts, packages/asset-swapper/src/utils/alt_mm_implementation_utils.ts, packages/asset-swapper/src/utils/market_operation_utils/types.ts, packages/asset-swapper/src/utils/quote_requestor.ts, packages/asset-swapper/src/utils/rfqt_mocker.ts, packages/asset-swapper/test/market_operation_utils_test.ts, packages/asset-swapper/test/quote_requestor_test.ts, packages/asset-swapper/test/utils/test_helpers.ts
Super tiny change to make Rfqt=>Rfq for types in Asset Swapper. This is because these types will be reused for RFQM
* Refactor
=> Rename {Rfqt=>Rfq} for types in Asset Swapper

packages/asset-swapper/src/utils/market_operation_utils/constants.ts, packages/asset-swapper/src/utils/market_operation_utils/index.ts, packages/asset-swapper/src/utils/quote_report_generator.ts, packages/asset-swapper/test/market_operation_utils_test.ts, packages/asset-swapper/test/quote_report_generator_test.ts
Fixes Quote Report so that is *only* reports the following:
- All RFQ sources “considered”
- The final sources “delivered” (the order salad delivered in the quote)
This should result in < 1% off the existing logging while providing the same value as before
=> Revive quote report

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts, packages/asset-swapper/src/swap_quoter.ts, packages/asset-swapper/src/utils/quote_simulation.ts, packages/asset-swapper/tslint.json
[TKR-39]
Hopefully fixes buy quotes inadvertently filling at 0% slippage when routing through the FQT/multiplex.
Update: it be do
=> Apply slippage to non-native orders [TKR-39]

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/src/utils/market_operation_utils/constants.ts
=> [asset-swapper] Support Ropsten testnet [TKR-16]

contracts/zero-ex/CHANGELOG.json, contracts/zero-ex/contracts/src/features/NativeOrdersFeature.sol
Version bump for the changes in https://github.com/0xProject/protocol/pull/195
=> bump NativeOrdersFeature version to 1.2

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/package.json, packages/asset-swapper/src/swap_quoter.ts, packages/asset-swapper/src/utils/market_operation_utils/constants.ts, packages/asset-swapper/src/utils/market_operation_utils/fills.ts, packages/asset-swapper/src/utils/market_operation_utils/path.ts, packages/asset-swapper/src/utils/market_operation_utils/path_optimizer.ts, packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts, packages/asset-swapper/test/market_operation_utils_test.ts, packages/contract-wrappers/src/generated-wrappers/broker.ts, packages/contract-wrappers/src/generated-wrappers/coordinator.ts, packages/contract-wrappers/src/generated-wrappers/dev_utils.ts, packages/contract-wrappers/src/generated-wrappers/erc20_token.ts, packages/contract-wrappers/src/generated-wrappers/erc721_token.ts, packages/contract-wrappers/src/generated-wrappers/exchange.ts, packages/contract-wrappers/src/generated-wrappers/forwarder.ts, packages/contract-wrappers/src/generated-wrappers/gods_unchained_validator.ts, packages/contract-wrappers/src/generated-wrappers/i_asset_data.ts, packages/contract-wrappers/src/generated-wrappers/i_liquidity_provider.ts, packages/contract-wrappers/src/generated-wrappers/i_transform_erc20.ts, packages/contract-wrappers/src/generated-wrappers/i_zero_ex.ts, packages/contract-wrappers/src/generated-wrappers/maximum_gas_price.ts, packages/contract-wrappers/src/generated-wrappers/staking.ts, packages/contract-wrappers/src/generated-wrappers/staking_proxy.ts, packages/contract-wrappers/src/generated-wrappers/weth9.ts, packages/contract-wrappers/src/index.ts, yarn.lock
TKR-24
[Simbot sells](https://metabase.spaceship.0x.org/dashboard/186?run_id=jacob-fast-abi--mainnet&adjusted_amount_bought_win_tolerance__bps_=0.5)
Prune paths where the rate (`bestRate`) when selling a fractional amount is less than the adjusted complete rate of selling the entire amount (`adjustedCompleteRate`) to the best source (sorted by `adjustedCompleteRate`).
Since selling anything to this path wouldn't result in any overall improvement. We can cut down on the paths to compare.
We should see no regressions, only improved response times (there is the small possibility of improved prices as we have more time to search over less paths)
Use an ABI encoder/decoder which is more performant than our AbiEncoder (though lacks the transaction gas optimization).
```
4000 USDC buy 
before: …
```
=> feat: Prune Paths + Fast ABI

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/src/utils/market_operation_utils/bridge_source_utils.ts, packages/asset-swapper/src/utils/market_operation_utils/constants.ts
Removes a reserve from Kyber which conflicted with a Liquidity Provider.
Perhaps it would be ideal if we only removed this reserve if PLP was included.
=> fix: Ban conflicting Kyber reserve

contracts/zero-ex/contracts/src/features/PancakeSwapFeature.sol, packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts
Need to update all references to forked values as `BakerySwap` is now `2` and `PancakeSwapV2` is `1`
Temporarily disabling VIP for these two sources
=> fix: Temporarily remove PancakeV2/Bakery from VIP

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/src/utils/market_operation_utils/index.ts
AssetSwapper was defaulting to an exchangeProxyGasOverhead of 0 when computing fallback orders. 
This PR fixes that logic
=> Fix exchangeProxyGasOverhead used to compute fallback orders

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/compiler.json, packages/asset-swapper/package.json
We probably care about having a smaller bytecode footprint than being efficient in the sampler since gas is free and we have to pass the full contract to the RPC endpoint for every eth_call.
Prev: ~51KB
Now: ~40KB
=> AS/Sampler: Tweak compiler settings for smaller sampler size

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/src/utils/market_operation_utils/pools_cache/balancer_sor_v2.ts, packages/asset-swapper/src/utils/market_operation_utils/pools_cache/balancer_utils.ts, packages/asset-swapper/src/utils/market_operation_utils/pools_cache/balancer_v2_utils.ts
This implements a slightly hacky solution to pre-populate the Balancer V2 pool cache on start-up so we avoid having empty a cache the first time we try to sample a token pair. Once Balance releases a new version of SOR that is compatible with both V1 and V2 we can remove the copy-pasta and clean this up 😄 
=> feat: Balancer V2 load and cache top pools by num swaps on startup [TKR-96]

packages/asset-swapper/src/swap_quoter.ts, packages/asset-swapper/src/utils/market_operation_utils/comparison_price.ts, packages/asset-swapper/src/utils/market_operation_utils/index.ts, packages/asset-swapper/src/utils/market_operation_utils/path.ts, packages/asset-swapper/src/utils/market_operation_utils/rate_utils.ts, packages/asset-swapper/src/utils/market_operation_utils/types.ts
TKR-166
Adds a new parameter to `ExchangeProxyOverhead`: `exchangeProxyOverhead(sourceFlags: bigint, numDistinctFills: number)`, where `numDistinctFills` is the number of unique `fill.sourcePathId`s in a `Path`.
Previously if we had a DAI->USDT multi-hop path like:
```
UniswapV3(DAI->WETH->USDC) -> UniswapV3(USDC->WETH->USDT)
```
the source flags would look like `SOURCE_FLAGS[UniswapV3] | SOURCE_FLAGS[UniswapV3] == SOURCE_FLAGS[UniswapV3]` which would trigger the (cheaper) EP overhead for UniswapV3 VIP even though this is not VIP compatible (there are two distinct uniswap V3 fills).
Now `exchangeProxyOverhead()` in API looks like:
```ts
exchangeProxyOverhead: (sourceFlags, numDistinctFills) => {
if (numDistinctFills === 1) {
// VIPs only support one "fill". Multi-hop uniswap paths are …
```
=> AS: Less ambiguous EP overhead [TKR-166]

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/src/utils/market_operation_utils/orders.ts
Paths don't often produce integer `output` values. Previously we were using this value directly to populate the `maxTakerFillAmount` in an FQT order. But for buys this can sometimes result in selling too little and causing an underbought error. This PR rounds up or down the path values to prevent this issue.
=> AS: Fix fill amount rounding error when converting to orders

contracts/erc20/CHANGELOG.json, contracts/erc20/package.json
Here's the problem: `0x/abi-gen`, which is used to build the contracts in `0x/contracts-erc20`, produces code specific to `ethers` v4. [An example from the TS template:](https://github.com/0xProject/tools/blob/5d17d8f4581e6a9f066d51530910e9b708cde661/abi-gen/templates/TypeScript/contract.handlebars#L151)
```
const iface = new ethers.utils.Interface(abi);
const deployInfo = iface.deployFunction;
const txData = deployInfo.encode(bytecode, [{{> params inputs=ctor.inputs}}]);
```
`deployFunction` is present in [ethers v4](https://docs.ethers.io/v4/api-advanced.html#id3), but v5 breaks this.
`ethers` is currently not a dependency of `@0x/contracts-erc20`. Therefore, if a package depends on `@0x/contracts-erc20`, to resolve `ethers` node will look in `@0x/contracts-erc20`'s `node_modules` and …
=> fix: Add ethers dependency to `0x/contracts-erc20`

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/contracts/src/ApproximateBuys.sol
In the `ApproximateBuys` ERC20BridgeSampler mixin we never really checked if we were actually hitting the requested buy amount when we loop to find the sell amount. The mooniswap USDT/DAI pool has only $180 in it so we saw a really great rate when trying to buy $300 because we were being quoted a really low sell amount for $300 without checking that we were actually buying $300 (which is impossible).  
For `swap/v1/quote?sellToken=DAI&buyToken=USDT&buyAmount=300000000`:
Before: `"price": "0.005448990721247178"`
After: `"price": "1.002948123432271921"`
=> Fix ApproximateBuys

packages/asset-swapper/src/constants.ts, packages/asset-swapper/src/index.ts, packages/asset-swapper/src/swap_quoter.ts, packages/asset-swapper/src/types.ts, packages/asset-swapper/src/utils/quote_requestor.ts, packages/asset-swapper/test/market_operation_utils_test.ts, packages/asset-swapper/test/quote_requestor_test.ts, packages/asset-swapper/test/utils/test_helpers.ts
1. Adds more Prometheus counters in the networking layer of HTTP(s) requests towards market makers
2. Adds a little more documentation and structure in the type formatting
3. Changes naming from `apiKey` to `integrator`
=> fix: Refactor integrator ID and add Prometheus metrics

docs/requirements.txt
Custom CSS seems to [have broken in Sphinx 4](https://github.com/sphinx-doc/sphinx/issues/2442).
Guessing readthedocs.io or their package repository upgraded the default
version of Sphinx to 4 and that caused our builds to start breaking.
They [recommend pinning dependencies](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#pinning-dependencies), let's do that here for Sphinx!
Check https://protocol.0x.org/en/fix-docs-css/, which is built from this branch!
Documentation
=> fix(docs): pin Sphinx version to 3.x to generate CSS

contracts/zero-ex/CHANGELOG.json, contracts/zero-ex/src/index.ts, packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/package.json, packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts, packages/asset-swapper/src/quote_consumers/multiplex_encoders.ts, packages/asset-swapper/src/quote_consumers/quote_consumer_utils.ts, packages/asset-swapper/test/exchange_proxy_swap_quote_consumer_test.ts, packages/contract-artifacts/CHANGELOG.json, packages/contract-artifacts/artifacts/ITransformERC20.json, packages/contract-artifacts/artifacts/IZeroEx.json, packages/contract-wrappers/CHANGELOG.json, packages/contract-wrappers/src/generated-wrappers/i_transform_erc20.ts, packages/contract-wrappers/src/generated-wrappers/i_zero_ex.ts, packages/contract-wrappers/src/index.ts, yarn.lock
As a recap, the plan is:
- Migrate MultiplexFeature and friends
- deploy the changes in this PR to 0x API (Ethereum only, BSC and Polygon stay put)
- update `transformERC20` on the EP
- update ExchangeProxySwapQuoteConsumer from `transformERC20Staging` back to `transformERC20`
- deregister `transformERC20Staging` and the old selectors from the EP
=> Update ExchangeProxySwapQuoteConsumer for MultiplexV2

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts
Multihop orders use `uint256(-1)` as intermediate amounts. We should not be applying slippage to those values in the consumer.
=> Fix ABI encoding error with two hop buys

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts, packages/asset-swapper/src/swap_quoter.ts, packages/asset-swapper/src/types.ts, packages/asset-swapper/test/exchange_proxy_swap_quote_consumer_test.ts, packages/asset-swapper/test/utils/swap_quote.ts
We had a base line amount of errors where there was inconsistent slippage between the Orders and what is recalculated in `getMaxQuoteSlippageRate`. To keep things consistent I think we just pass it around in the `worstCaseQuoteInfo` which has already been adjusted by that amount of slippage.
For example, the order would be adjusted by 0.005 slippage and the calculated slippage would be 0.005011....
This could create an inconsistency with the `sellAmount` encoded and the FQT data encoded
```
{
"functionName": "IncompleteFillSellQuoteError",
"functionSignature": "adc35ca6",
"functionArguments": [
"IncompleteFillSellQuoteError({\n  sellToken: '0x2791bca1f2de4661ed88a30c99a7a9449aa84174',\n  soldAmount: 29303021,\n  sellAmount: 29303022\n})"
]
}
```
-   [ ] Prefix PR title with `[WIP]` if …
=> fix: slippage inconsistency when recalculated in exchange proxy quote consumer

contracts/erc20/package.json, contracts/test-utils/package.json, contracts/treasury/package.json, contracts/utils/package.json, contracts/zero-ex/package.json, package.json, packages/asset-swapper/package.json, packages/contract-addresses/package.json, packages/contract-artifacts/package.json, packages/contract-wrappers/package.json, packages/migrations/package.json, packages/protocol-utils/package.json, tsconfig.json, yarn.lock
This fixes the [ethereumjs TypeScript issue](https://app.circleci.com/pipelines/github/0xProject/protocol/3290/workflows/44f17c3a-b513-4c7d-8d1b-d4e364b78c05/jobs/16440) blocking publishing by upgrading our TS version to 4.6
=> chore: bump ts version to solve type issue with ethereumjs

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/src/utils/market_operation_utils/index.ts, packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts
Initializing `BalancerV2SwapInfoCache` on an unsupported chain causes a runtime error as `BalancerSDK` tries to read undefined properties.
Tested locally that this change prevents runtime error on a chain where Balancer V2 is not supported.
* Bug fix (non-breaking change which fixes an issue) 
=> Do not initialize BalancerV2SwapInfoCache on unsupported chains [TKR-365]

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/src/utils/market_operation_utils/bridge_source_utils.ts, packages/asset-swapper/src/utils/market_operation_utils/constants.ts, packages/asset-swapper/src/utils/market_operation_utils/orders.ts, packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts, packages/asset-swapper/src/utils/market_operation_utils/types.ts
Add Yoshi Exchange support in Fantom
Run 0x-api locally. 
* New feature (non-breaking change which adds functionality) 
=> Add Yoshi Exchange support (Fantom) [TKR-270]

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/src/utils/market_operation_utils/constants.ts, packages/asset-swapper/src/utils/market_operation_utils/pools_cache/balancer_v2_utils.ts, packages/asset-swapper/src/utils/market_operation_utils/sampler_operations.ts, packages/asset-swapper/src/utils/market_operation_utils/types.ts, packages/asset-swapper/test/pools_cache_test.ts, packages/asset-swapper/tsconfig.ts-prune.json
Bug Fix:
* Replace Beethoven X subgraph .
Improvements:
* Do not create `BalancerV2PoolsCache` on unsupported chains.
* Add `BalancerV2PoolsCache` test for Beethoven X.
* Remove `BalancerV2PoolsCache` test for Balancer V2 (no longer used in production). 
* Simplify `PoolsCacheMap` type.
-   [ ] Add new entries to the relevant CHANGELOG.jsons. (will be updated before this PR is merged)
=> Fix Beethoven X Cache Issue [TKR-486]

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/package.json, packages/asset-swapper/src/constants.ts, packages/asset-swapper/src/swap_quoter.ts, packages/asset-swapper/src/types.ts, packages/asset-swapper/src/utils/protocol_fee_utils.ts, packages/asset-swapper/test/protocol_fee_utils_test.ts, packages/asset-swapper/tslint.json, yarn.lock
Context: 
* eth gas station api's gas price granularity is 1/10 gwei. While this level of precision has been good enough for most chains, that is no longer the case. For example, at the time of writing, Optimism gas price (fast) is 0.001 gwei. 
Change:
* Use 0x gas api which returns gas prices in wei 
=> Use 0x gas api instead of eth gas station api [TKR-502]

packages/asset-swapper/src/constants.ts, packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts, packages/asset-swapper/src/utils/alt_mm_implementation_utils.ts, packages/asset-swapper/src/utils/market_operation_utils/aave_reserves_cache.ts, packages/asset-swapper/src/utils/market_operation_utils/compound_ctoken_cache.ts, packages/asset-swapper/src/utils/market_operation_utils/constants.ts, packages/asset-swapper/src/utils/market_operation_utils/path_optimizer.ts, packages/asset-swapper/src/utils/market_operation_utils/pools_cache/balancer_utils.ts, packages/asset-swapper/src/utils/market_operation_utils/pools_cache/balancer_v2_utils.ts, packages/asset-swapper/src/utils/market_operation_utils/pools_cache/balancer_v2_utils_new.ts, packages/asset-swapper/src/utils/market_operation_utils/pools_cache/pair_swaps_cache.ts, packages/asset-swapper/src/utils/market_operation_utils/pools_cache/pools_cache.ts
`custom-no-magic-numbers` have been disabled in a previous PR. 
This PR removes the remaining references to the disabled rule. 
=> Remove references to `custom-no-magic-numbers` ts lint rule [TKR-484]

contracts/erc20/src/artifacts.ts, contracts/erc20/test/artifacts.ts, contracts/zero-ex/contracts/src/transformers/FillQuoteTransformer.sol, contracts/zero-ex/test/artifacts.ts, packages/protocol-utils/CHANGELOG.json, packages/protocol-utils/src/transformer_utils.ts
swap rfq and otc in fillQuoteTransformerDataEncoder to match our enum
=> Fix: FQT otc order encoding logic

.prettierignore, contracts/zero-ex/contracts/src/transformers/AffiliateFeeTransformer.sol, contracts/zero-ex/contracts/src/transformers/LibERC20Transformer.sol, contracts/zero-ex/contracts/src/transformers/PayTakerTransformer.sol, contracts/zero-ex/contracts/src/transformers/PositiveSlippageFeeTransformer.sol
* Since `transfer` only forwards 2300 gas it can cause an `out of gas` revert when the receipient is a smart contract.
=> fix: Migrate transformers to smart contract compatible `unsafeTransformerTransfer` [TKR-587]

contracts/zero-ex/contracts/src/transformers/bridges/FantomBridgeAdapter.sol
Removing both Aave V2 and Aave V3 from Fantom's Bridge Adapter. Aave V2 is not supported on Fantom and Aave V3 lending activity is frozen on Fantom.
=> chore: removing Aave V2 and Aave V3 from Fantom

.github/autolabeler.yml, .github/stale.yml
Updating [autolabeller](https://github.com/apps/probot-autolabeler) process in github to assign `documentation` and `liquidity integrations` labels to `/docs` and `contracts/zero-ex/contracts/src/transformers` changes.
Also switching the stale autolabeller to close after 14 days.
Closes https://linear.app/0xproject/issue/GOV-34/update-github-labels
=> Update auto labeller and stale bot for issues and PRs

contracts/zero-ex/CHANGELOG.json, contracts/zero-ex/contracts/src/transformers/bridges/AbstractBridgeAdapter.sol
Skip chain id validation in `AbstractBridgeAdapter` on testnets so that a chain specific bridge adapter can be re-used on testnets (e.g. deploying `EthereumBridgeAdapter` on Goerli). 
-   [x] Add tests to cover changes as needed - n/a
-   [x] Update documentation as needed. - n/a
=> chore: Skip chain id validation in `AbstractBridgeAdapter` on testnets

contracts/erc20/CHANGELOG.json
Publish was failing https://github.com/0xProject/protocol/actions/runs/4289008519/jobs/7471624112
```
Error: Found CHANGELOG version lower then current package version. @0x/contracts-erc20 current: 4.0.0, Changelog: 3.3.57
at Object.shouldAddNewChangelogEntry (/home/runner/work/protocol/protocol/node_modules/@0x/monorepo-scripts/lib/utils/changelog_utils.js:58:19)
at /home/runner/work/protocol/protocol/node_modules/@0x/monorepo-scripts/lib/publish.js:172:72
at Generator.next (<anonymous>)
at fulfilled (/home/runner/work/protocol/protocol/node_modules/@0x/monorepo-scripts/lib/publish.js:6:58)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
-   [ ] Add new entries to the relevant …
=> chore: update erc20 changelog to match .md file

contracts/zero-ex/contracts/src/transformers/bridges/ArbitrumBridgeAdapter.sol, contracts/zero-ex/contracts/src/transformers/bridges/AvalancheBridgeAdapter.sol, contracts/zero-ex/contracts/src/transformers/bridges/OptimismBridgeAdapter.sol, contracts/zero-ex/contracts/src/transformers/bridges/PolygonBridgeAdapter.sol, contracts/zero-ex/contracts/src/transformers/bridges/mixins/MixinAaveV3.sol
Removing the L2 Encoding for Aave V3 MixIn. The L2 encoding makes settlement more brittle and is causing some high revert rates specifically for MultiHop tokens involving Aave V3 tokens. 
Breaking change (fix or feature that would cause existing functionality to change)
=> feat: removing L2 Encoding from AaveV3 MixIn [LIT-901]

contracts/governance/src/ZRXWrappedToken.sol, contracts/governance/src/ZeroExVotes.sol, contracts/governance/test/BaseTest.t.sol, contracts/governance/test/ZeroExVotesTest.t.sol
=> Make addresses immutable

.gitignore, contracts/governance/src/ZeroExVotes.sol, contracts/governance/test/CubeRoot.sol, contracts/governance/test/ZeroExVotesMigration.sol, contracts/governance/test/ZeroExVotesTest.t.sol
Add a migration test for the voting logic. We simulate upgrading this to add a cube root vote weight mechanism. This utilizes of the currently unused `DelegateInfo.balanceLastUpdated` property which is passed to the voting contract by the wrapped token.
=> Test votes migration for adding a new vote weight mechanism

contracts/zero-ex/tests/forked/SwapEthForERC20Test.t.sol
`SwapEthForERC20Test` has been failing all builds for the past couple of days blocking work. Fudging it here so I can merge a bunch of governance PRs.
For traceability, logged the issue to resolve this test here https://github.com/0xProject/protocol/issues/693
=> Fudge broken build

contracts/governance/test/integration/GovernanceE2E.t.sol
Add integration test for withdrawing 0x stake and delegating in the new governance system.
We've tested both scenarios of this run in catastrophic mode as well as under normal v3 staking operation.
Closes https://linear.app/0xproject/issue/GOV-130/switch-delegation
=> Integration test for migrating 0x stake

.github/workflows/publish.yml
Forge was added to the CI action but not the publish action.
=> chore: add forge to publish action

packages/contract-artifacts/CHANGELOG.json, packages/contract-artifacts/artifacts/IZeroEx.json, packages/contract-wrappers/CHANGELOG.json, packages/contract-wrappers/src/generated-wrappers/i_zero_ex.ts, packages/protocol-utils/CHANGELOG.json, packages/protocol-utils/src/index.ts, packages/protocol-utils/src/meta_transactions_v2.ts, packages/protocol-utils/test/meta_transactions_v2_test.ts
Accompanying typescript utilities for #665 
```
cd packages/protocol-utils
yarn test --fgrep "mtxs v2"
```
=> MetaTransaction V2 Packages

contracts/erc20/test/WETH9V06Test.t.sol, contracts/erc20/test/ZRXTokenTest.t.sol, contracts/governance/test/unit/ZeroExGovernorBaseTest.t.sol, contracts/governance/test/unit/ZeroExProtocolGovernor.t.sol, contracts/governance/test/unit/ZeroExTreasuryGovernor.t.sol
Closes LIT-1020. 
tl;dr: Foundry CI tests are failing due to the new version of forge reverting if we call `vm.stopPrank` without calling `vm.startPrank`.
Bug fix (non-breaking change which fixes an issue)
=> fix: remove vm.stopPrank if vm.startPrank not present

contracts/zero-ex/tests/MetaTransactionV2Test.t.sol
We are using forge's `vm.expectEmit` incorrectly in a few tests causing the tests to fail. This change corrects our usage in `MetaTransactionV2Test.t.sol`. The tests were previously passing, perhaps because of some bug in forge that must have been patched recently.
`forge test --match-contract MetaTransactionTest`
* Bug fix (non-breaking change which fixes an issue)
=> Fix usage of expectEmit in MetaTransactionsFeatureV2 tests

contracts/zero-ex/CHANGELOG.json, contracts/zero-ex/contracts/src/transformers/bridges/AvalancheBridgeAdapter.sol, contracts/zero-ex/contracts/src/transformers/bridges/BSCBridgeAdapter.sol, contracts/zero-ex/contracts/src/transformers/bridges/mixins/MixinUniswapV3.sol, packages/contract-addresses/CHANGELOG.json, packages/contract-addresses/addresses.json
* Fixes LIT-1176
* Add Uniswap V3 to Avalanche and BSC bridge adapters
* Add router v2 support in `MixinUniswapV3` (backward compatible)
* This change is needed as newer Uniswap V3 deployments do not have router v1 (e.g. BSC, Avalanche).
* Update Avalanche/BSC FillQuoteTransformer addresses 
* New feature (non-breaking change which adds functionality)
=> Add UniswapV3 to Avalanche and BSC bridge adapters

contracts/zero-ex/tests/transformers/bridges/OptimismBridgeAdapterTest.t.sol
Adding a test to check compatibility of Velodrome V2 with the Optimism Bridge Adapter.
=> Add Velodrome V2 compatibility test to Optimism Bridge Adapter Test
